version: 2
updates:
  # Frontend dependencies (SvelteKit)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      svelte:
        patterns:
          - "@sveltejs/*"
          - "svelte*"
      storybook:
        patterns:
          - "@storybook/*"
          - "storybook"
      testing:
        patterns:
          - "@playwright/*"
          - "playwright"
          - "@vitest/*"
          - "vitest"
          - "@testing-library/*"
      eslint:
        patterns:
          - "eslint*"
          - "@eslint/*"

  # Backend dependencies (Python/Poetry)
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Docker
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # GitHub Actions (if you add any)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
