# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        # Refined exclude pattern
        exclude: '(^|.*/)node_modules/|(^|.*/)source_data/'
    -   id: end-of-file-fixer
        exclude: '(^|.*/)node_modules/|(^|.*/)source_data/|^frontend/'
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 25.1.0 # Match the version in pyproject.toml
    hooks:
    -   id: black
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1 # Match the version in pyproject.toml
    hooks:
    -   id: isort
        name: isort (python)
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version matches the one in pyproject.toml
    rev: v0.11.9
    hooks:
    -   id: ruff
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
        args: [--fix, --exit-non-zero-on-fix] # Apply fixes automatically
    -   id: ruff-format
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
        args: [--fix, --exit-non-zero-on-fix] # Apply fixes automatically

# Frontend hooks using Node.js environment
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.18.0
    hooks:
    -   id: eslint
        files: ^frontend/src/.*\.(js|jsx|ts|tsx|svelte)$
        additional_dependencies:
        - eslint@^9.18.0
        - typescript-eslint@^8.20.0
        - eslint-plugin-svelte@^3.0.0
        - eslint-config-prettier@^10.0.1
        args: [--fix]
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.4.2
    hooks:
    -   id: prettier
        files: ^frontend/src/.*\.(js|jsx|ts|tsx|svelte|json|css|md)$
        additional_dependencies:
        - prettier@^3.4.2
        - prettier-plugin-svelte@^3.3.3
        - prettier-plugin-tailwindcss@^0.6.11
