# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    -   id: trailing-whitespace
        # Refined exclude pattern
        exclude: '(^|.*/)node_modules/|(^|.*/)source_data/'
    -   id: end-of-file-fixer
        exclude: '(^|.*/)node_modules/|(^|.*/)source_data/|^frontend/'
    -   id: check-yaml
    -   id: check-toml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 25.1.0 # Match the version in pyproject.toml
    hooks:
    -   id: black
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
-   repo: https://github.com/pycqa/isort
    rev: 6.0.1 # Match the version in pyproject.toml
    hooks:
    -   id: isort
        name: isort (python)
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version matches the one in pyproject.toml
    rev: v0.11.9
    hooks:
    -   id: ruff
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
        args: [--fix, --exit-non-zero-on-fix] # Apply fixes automatically
    -   id: ruff-format
        # Ensure this ONLY targets backend/src python files
        files: ^backend/src/.*\\.py$
        args: [--fix, --exit-non-zero-on-fix] # Apply fixes automatically

# Hook for Frontend Linting (runs inside Docker)
-   repo: local
    hooks:
    -   id: frontend-lint
        name: frontend-lint (eslint & prettier)
        entry: docker compose exec frontend yarn lint
        language: system
        types: [javascript, jsx, ts, tsx] # Only run on relevant file types
        files: ^frontend/src/.*
        pass_filenames: false # We don't need to pass filenames, lint runs on the whole dir
