services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/project
      - ./backend/src:/app/src
      - ./public:/app/public
      - ./scripts:/app/scripts
    environment:
      APP_VERSION: 0.1.0
