services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/project
      - ./backend/src:/app/src
      - ./scripts:/app/scripts
    environment:
      APP_VERSION: 0.1.0

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    # Optional: Depends on backend starting first, though not strictly required for dev
    # depends_on:
    #   - backend
