services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .app:/home/appuser/app/app
      - ./pyproject.toml:/home/appuser/app/pyproject.toml
    environment:
      - DATABASE_URL=neo4j://neo4j:7687

  neo4j:
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "7474:7474"
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=4G
      - NEO4J_AUTH=neo4j/your_password
  
volumes:
  neo4j_data:
