[tool.poetry]
name = "bmx-bookmark-extractor"
version = "0.1.0"
description = ""
authors = ["CooperR1 <cooperability@gmail.com>"]
readme = "README.md"
packages = [{include = "bmx_bookmark_extractor"}]

[tool.poetry.dependencies]
python = "^3.10"
pip = "^23.3"
spacy = "^3.6.0"
scrapy = "^2.11.2"
numpy = "^1.25.1"
keras = "^2.13.1"
matplotlib = "^3.7.2"
pandas = "^2.0.3"
nltk = "^3.8.1"
scikit-learn = "^1.5.0"
django = "^4.2.11"
psycopg2 = "^2.9.7"
bs4 = "^0.0.1"
requests = "^2.32.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
