#An article can only have one author (database schema)
#variables with a ! are required
type Article {
  id: String!
  url: String!
  name: String!
  date: String!
  author: Author!
}

#An author can have multiple articles stored in a collection
type Author {
  name: String!
  url: String!
  articles: [Article]
}

#The query is the entry point to read data
type Query {
  articles: [Article]
  author(id: String!): Author
}

#The mutation is the entry point to modify data
type Mutation {
  createArticle(url: String): Article
  deleteArticle(url: String): String
}
