document.addEventListener("DOMContentLoaded", function () {
    const contentDiv = document.getElementById("content");

    // Create and append elements to the content div
    const heading = document.createElement("h1");
    heading.textContent = "Hello, TypeScript!";
    if (contentDiv) { contentDiv.appendChild(heading); }

    const paragraph = document.createElement("p");
    paragraph.textContent = "This content is generated by TypeScript.";
    if (contentDiv) { contentDiv.appendChild(paragraph) }

    // You can further manipulate the DOM as needed
});

export default function Home() {
    alert("Alert works");
    console.log("Console commands work");
    return (
        <div
            style={{
                display: "flex",
                justifyContent: "space-evenly",
                marginTop: "20px",
            }}
        >
            <button onClick={() => { alert('Hola') }}>It works!</button>
        </div>
    );
}
