# Generated by Django 4.2.5 on 2023-09-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpage',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
